services:
  msvc-usuarios:
    container_name: msvc-usuarios
    #    image: elreyhamlet/usuarios
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    restart: always
